/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gsuaki.avro.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ArtistRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1491355962850632628L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ArtistRecord\",\"namespace\":\"com.gsuaki.avro.models\",\"fields\":[{\"name\":\"artist_name\",\"type\":\"string\"},{\"name\":\"cache\",\"type\":\"int\"},{\"name\":\"cities\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ArtistRecord> ENCODER =
      new BinaryMessageEncoder<ArtistRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ArtistRecord> DECODER =
      new BinaryMessageDecoder<ArtistRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ArtistRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ArtistRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ArtistRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ArtistRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ArtistRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ArtistRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ArtistRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ArtistRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence artist_name;
  private int cache;
  private java.util.List<java.lang.CharSequence> cities;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ArtistRecord() {}

  /**
   * All-args constructor.
   * @param artist_name The new value for artist_name
   * @param cache The new value for cache
   * @param cities The new value for cities
   */
  public ArtistRecord(java.lang.CharSequence artist_name, java.lang.Integer cache, java.util.List<java.lang.CharSequence> cities) {
    this.artist_name = artist_name;
    this.cache = cache;
    this.cities = cities;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return artist_name;
    case 1: return cache;
    case 2: return cities;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: artist_name = (java.lang.CharSequence)value$; break;
    case 1: cache = (java.lang.Integer)value$; break;
    case 2: cities = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'artist_name' field.
   * @return The value of the 'artist_name' field.
   */
  public java.lang.CharSequence getArtistName() {
    return artist_name;
  }


  /**
   * Sets the value of the 'artist_name' field.
   * @param value the value to set.
   */
  public void setArtistName(java.lang.CharSequence value) {
    this.artist_name = value;
  }

  /**
   * Gets the value of the 'cache' field.
   * @return The value of the 'cache' field.
   */
  public int getCache() {
    return cache;
  }


  /**
   * Sets the value of the 'cache' field.
   * @param value the value to set.
   */
  public void setCache(int value) {
    this.cache = value;
  }

  /**
   * Gets the value of the 'cities' field.
   * @return The value of the 'cities' field.
   */
  public java.util.List<java.lang.CharSequence> getCities() {
    return cities;
  }


  /**
   * Sets the value of the 'cities' field.
   * @param value the value to set.
   */
  public void setCities(java.util.List<java.lang.CharSequence> value) {
    this.cities = value;
  }

  /**
   * Creates a new ArtistRecord RecordBuilder.
   * @return A new ArtistRecord RecordBuilder
   */
  public static com.gsuaki.avro.models.ArtistRecord.Builder newBuilder() {
    return new com.gsuaki.avro.models.ArtistRecord.Builder();
  }

  /**
   * Creates a new ArtistRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ArtistRecord RecordBuilder
   */
  public static com.gsuaki.avro.models.ArtistRecord.Builder newBuilder(com.gsuaki.avro.models.ArtistRecord.Builder other) {
    if (other == null) {
      return new com.gsuaki.avro.models.ArtistRecord.Builder();
    } else {
      return new com.gsuaki.avro.models.ArtistRecord.Builder(other);
    }
  }

  /**
   * Creates a new ArtistRecord RecordBuilder by copying an existing ArtistRecord instance.
   * @param other The existing instance to copy.
   * @return A new ArtistRecord RecordBuilder
   */
  public static com.gsuaki.avro.models.ArtistRecord.Builder newBuilder(com.gsuaki.avro.models.ArtistRecord other) {
    if (other == null) {
      return new com.gsuaki.avro.models.ArtistRecord.Builder();
    } else {
      return new com.gsuaki.avro.models.ArtistRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for ArtistRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ArtistRecord>
    implements org.apache.avro.data.RecordBuilder<ArtistRecord> {

    private java.lang.CharSequence artist_name;
    private int cache;
    private java.util.List<java.lang.CharSequence> cities;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gsuaki.avro.models.ArtistRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.artist_name)) {
        this.artist_name = data().deepCopy(fields()[0].schema(), other.artist_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.cache)) {
        this.cache = data().deepCopy(fields()[1].schema(), other.cache);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.cities)) {
        this.cities = data().deepCopy(fields()[2].schema(), other.cities);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ArtistRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gsuaki.avro.models.ArtistRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.artist_name)) {
        this.artist_name = data().deepCopy(fields()[0].schema(), other.artist_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cache)) {
        this.cache = data().deepCopy(fields()[1].schema(), other.cache);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cities)) {
        this.cities = data().deepCopy(fields()[2].schema(), other.cities);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'artist_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getArtistName() {
      return artist_name;
    }


    /**
      * Sets the value of the 'artist_name' field.
      * @param value The value of 'artist_name'.
      * @return This builder.
      */
    public com.gsuaki.avro.models.ArtistRecord.Builder setArtistName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.artist_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'artist_name' field has been set.
      * @return True if the 'artist_name' field has been set, false otherwise.
      */
    public boolean hasArtistName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'artist_name' field.
      * @return This builder.
      */
    public com.gsuaki.avro.models.ArtistRecord.Builder clearArtistName() {
      artist_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cache' field.
      * @return The value.
      */
    public int getCache() {
      return cache;
    }


    /**
      * Sets the value of the 'cache' field.
      * @param value The value of 'cache'.
      * @return This builder.
      */
    public com.gsuaki.avro.models.ArtistRecord.Builder setCache(int value) {
      validate(fields()[1], value);
      this.cache = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'cache' field has been set.
      * @return True if the 'cache' field has been set, false otherwise.
      */
    public boolean hasCache() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cache' field.
      * @return This builder.
      */
    public com.gsuaki.avro.models.ArtistRecord.Builder clearCache() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cities' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getCities() {
      return cities;
    }


    /**
      * Sets the value of the 'cities' field.
      * @param value The value of 'cities'.
      * @return This builder.
      */
    public com.gsuaki.avro.models.ArtistRecord.Builder setCities(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.cities = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cities' field has been set.
      * @return True if the 'cities' field has been set, false otherwise.
      */
    public boolean hasCities() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cities' field.
      * @return This builder.
      */
    public com.gsuaki.avro.models.ArtistRecord.Builder clearCities() {
      cities = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ArtistRecord build() {
      try {
        ArtistRecord record = new ArtistRecord();
        record.artist_name = fieldSetFlags()[0] ? this.artist_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.cache = fieldSetFlags()[1] ? this.cache : (java.lang.Integer) defaultValue(fields()[1]);
        record.cities = fieldSetFlags()[2] ? this.cities : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ArtistRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<ArtistRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ArtistRecord>
    READER$ = (org.apache.avro.io.DatumReader<ArtistRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.artist_name);

    out.writeInt(this.cache);

    long size0 = this.cities.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.cities) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.artist_name = in.readString(this.artist_name instanceof Utf8 ? (Utf8)this.artist_name : null);

      this.cache = in.readInt();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.cities;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("cities").schema());
        this.cities = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.artist_name = in.readString(this.artist_name instanceof Utf8 ? (Utf8)this.artist_name : null);
          break;

        case 1:
          this.cache = in.readInt();
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.cities;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("cities").schema());
            this.cities = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










